name: ci-cd
on:
  push:
  pull_request:
  release:
    types:
      - 'published'
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Unit Tests
        run: yarn jest tests/unit --coverage
      - name: E2E Tests
        run: echo "TODO"
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: quality
    if: github.event_name == 'release'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=result::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            opennps/opennps:${{ steps.tag.outputs.result }}
            opennps/opennps:latest
