name: ci-cd
on:
  push:
  pull_request:
  release:
    types:
      - 'published'
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Unit Tests
        run: yarn jest tests/unit --coverage

  chrome:
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000/api/healthcheck
          browser: chrome
          parallel: true
          group: 'E2E Tests'
          ci-build-id: ${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGO_URL: mongodb://localhost:27017/open-nps

  build_and_deploy:
    runs-on: ubuntu-latest
    needs:
      - chrome
    if: github.event_name == 'release'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=result::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            opennps/opennps:${{ steps.tag.outputs.result }}
            opennps/opennps:latest
