name: ci-cd
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Unit Tests
        run: yarn jest test/unit --coverage
      - name: E2E Tests
        run: echo "TODO"
